# Generated by Django 6.0.3 on 2026-07-27 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ai_conversation', serialize=False, to='requests.request')),
                ('context', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'AI Conversation',
                'verbose_name_plural': 'AI Conversations',
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('USER', 'Người dùng'), ('ASSISTANT', 'Trợ lý AI')], max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assist.aiconversation')),
            ],
            options={
                'verbose_name': 'AI Message',
                'verbose_name_plural': 'AI Messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
