# Generated by Django 6.0.3 on 2026-07-19 08:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('MAJOR_CHANGE', 'Chuyển ngành'), ('ACADEMIC_LEAVE', 'Ngừng học'), ('RESUME_STUDIES', 'Tiếp tục học'), ('DROPOUT', 'Thôi học')], max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('PENDING_REVIEW', 'Chờ tiếp nhận'), ('IN_PROGRESS', 'Đang xử lý'), ('ADDITIONAL_INFO_REQUIRED', 'Yêu cầu bổ sung'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('CANCELLED', 'Đã hủy')], db_index=True, default='DRAFT', max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày gửi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='students.student')),
            ],
            options={
                'verbose_name': 'Yêu cầu',
                'verbose_name_plural': 'Các yêu cầu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicLeaveRequest',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='academic_leave_request', serialize=False, to='requests.request')),
                ('reason', models.TextField(verbose_name='Lý do ngừng học')),
            ],
        ),
        migrations.CreateModel(
            name='DropoutRequest',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dropout_request', serialize=False, to='requests.request')),
                ('reason', models.TextField(verbose_name='Lý do thôi học')),
            ],
        ),
        migrations.CreateModel(
            name='MajorChangeRequest',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='major_change_request', serialize=False, to='requests.request')),
                ('reason', models.TextField(verbose_name='Lý do chuyển ngành')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeStudiesRequest',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='resume_studies_request', serialize=False, to='requests.request')),
                ('reason', models.TextField(verbose_name='Lý do tiếp tục học')),
            ],
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('PENDING_REVIEW', 'Chờ tiếp nhận'), ('IN_PROGRESS', 'Đang xử lý'), ('ADDITIONAL_INFO_REQUIRED', 'Yêu cầu bổ sung'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('CANCELLED', 'Đã hủy')], max_length=50, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='requests.request')),
            ],
            options={
                'verbose_name': 'Lịch sử xử lý',
                'verbose_name_plural': 'Lịch sử xử lý',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['student', 'status'], name='requests_re_student_03306e_idx'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['APPROVED', 'REJECTED', 'CANCELLED']), _negated=True), fields=('student',), name='unique_active_request_per_student'),
        ),
    ]
