# Generated by Django 6.0.3 on 2026-07-27 08:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('MAJOR_CHANGE', 'Chuyển ngành'), ('ACADEMIC_LEAVE', 'Ngừng học'), ('RESUME_STUDIES', 'Tiếp tục học'), ('DROPOUT', 'Thôi học')], max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('PENDING_REVIEW', 'Chờ tiếp nhận'), ('IN_PROGRESS', 'Đang xử lý'), ('ADDITIONAL_INFO_REQUIRED', 'Yêu cầu bổ sung'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('CANCELLED', 'Đã hủy')], db_index=True, default='DRAFT', max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày gửi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
            ],
            options={
                'verbose_name': 'Yêu cầu',
                'verbose_name_plural': 'Các yêu cầu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('PENDING_REVIEW', 'Chờ tiếp nhận'), ('IN_PROGRESS', 'Đang xử lý'), ('ADDITIONAL_INFO_REQUIRED', 'Yêu cầu bổ sung'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('CANCELLED', 'Đã hủy')], max_length=50, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
            ],
            options={
                'verbose_name': 'Lịch sử xử lý',
                'verbose_name_plural': 'Lịch sử xử lý',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AcademicLeaveRequest',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='academic_leave_request', serialize=False, to='requests.request')),
                ('reason', models.TextField(verbose_name='Lý do ngừng học')),
            ],
            options={
                'verbose_name': 'Yêu cầu Ngừng học',
                'verbose_name_plural': 'Yêu cầu Ngừng học',
            },
        ),
        migrations.CreateModel(
            name='DropoutRequest',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dropout_request', serialize=False, to='requests.request')),
                ('reason', models.TextField(verbose_name='Lý do thôi học')),
            ],
            options={
                'verbose_name': 'Yêu cầu Thôi học',
                'verbose_name_plural': 'Yêu cầu Thôi học',
            },
        ),
        migrations.CreateModel(
            name='MajorChangeRequest',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='major_change_request', serialize=False, to='requests.request')),
                ('reason', models.TextField(verbose_name='Lý do chuyển ngành')),
            ],
            options={
                'verbose_name': 'Yêu cầu Chuyển ngành',
                'verbose_name_plural': 'Yêu cầu Chuyển ngành',
            },
        ),
        migrations.CreateModel(
            name='ResumeStudiesRequest',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='resume_studies_request', serialize=False, to='requests.request')),
                ('reason', models.TextField(verbose_name='Lý do tiếp tục học')),
            ],
            options={
                'verbose_name': 'Yêu cầu Tiếp tục học',
                'verbose_name_plural': 'Yêu cầu Tiếp tục học',
            },
        ),
    ]
