# Generated by Django 6.0.3 on 2026-07-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumestudiesrequest',
            name='reason',
        ),
        migrations.AddField(
            model_name='resumestudiesrequest',
            name='courses',
            field=models.JSONField(default=list, verbose_name='Danh sách học phần dự kiến'),
        ),
    ]
