# Generated by Django 6.0.3 on 2026-07-28 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_remove_resumestudiesrequest_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=255, upload_to='request_documents/')),
                ('document_type', models.CharField(choices=[('INITIAL', 'Hồ sơ ban đầu'), ('SUPPLEMENTARY', 'Hồ sơ bổ sung')], default='INITIAL', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='requests.request')),
            ],
            options={
                'verbose_name': 'Tài liệu đính kèm',
                'verbose_name_plural': 'Tài liệu đính kèm',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
