# Generated by Django 6.0.3 on 2026-07-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_requestdocument'),
        ('students', '0003_major_faculty_name_student_phone'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='request',
            name='unique_active_request_per_student',
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Bản nháp'), ('PENDING', 'Chờ xử lý'), ('ADDITIONAL_INFO_REQUIRED', 'Yêu cầu bổ sung'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('DELETED', 'Đã xóa')], db_index=True, default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Bản nháp'), ('PENDING', 'Chờ xử lý'), ('ADDITIONAL_INFO_REQUIRED', 'Yêu cầu bổ sung'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('DELETED', 'Đã xóa')], max_length=50, verbose_name='Trạng thái'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['APPROVED', 'REJECTED', 'DELETED']), _negated=True), fields=('student',), name='unique_active_request_per_student'),
        ),
    ]
