# Generated by Django 5.2.16 on 2026-07-29 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_requestdocument'),
        ('students', '0003_major_faculty_name_student_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('MAJOR_CHANGE', 'Chuyển ngành'), ('ACADEMIC_LEAVE', 'Ngừng học'), ('RESUME_STUDIES', 'Tiếp tục học'), ('DROPOUT', 'Thôi học')], max_length=50)),
                ('is_started', models.BooleanField(default=False)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('draft_data', models.JSONField(blank=True, default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_drafts', to='students.student')),
            ],
            options={
                'verbose_name': 'Bản nháp thủ tục',
                'verbose_name_plural': 'Các bản nháp thủ tục',
                'constraints': [models.UniqueConstraint(fields=('student', 'request_type'), name='unique_procedure_draft_per_student_and_type')],
            },
        ),
    ]
