# Generated by Django 5.2.16 on 2026-08-03 01:42

import apps.requests.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_proceduredraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureDraftDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_key', models.CharField(choices=[('DROPOUT_SIGNED_APPLICATION', 'Đơn thôi học đã ký'), ('ACADEMIC_LEAVE_EVIDENCE', 'Minh chứng bảo lưu'), ('ACADEMIC_LEAVE_SIGNED_APPLICATION', 'Đơn bảo lưu đã ký'), ('RESUME_SIGNED_APPLICATION', 'Đơn học tiếp đã ký'), ('MAJOR_CHANGE_ADMISSION_LETTER', 'Giấy báo trúng tuyển'), ('MAJOR_CHANGE_GRADUATION_CERTIFICATE', 'Giấy chứng nhận tốt nghiệp THPT'), ('MAJOR_CHANGE_SIGNED_APPLICATION', 'Đơn chuyển ngành đã ký')], max_length=100)),
                ('file', models.FileField(max_length=500, upload_to=apps.requests.models.procedure_draft_document_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='requests.proceduredraft')),
            ],
            options={
                'verbose_name': 'Tài liệu bản nháp',
                'verbose_name_plural': 'Các tài liệu bản nháp',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('draft', 'document_key'), name='unique_document_key_per_procedure_draft')],
            },
        ),
    ]
