# Generated by Django 6.0.3 on 2026-07-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_remove_request_unique_active_request_per_student_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='request',
            name='unique_active_request_per_student',
        ),
    ]
