# Generated by Django 5.2.16 on 2026-08-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_proceduredraftdocument'),
        ('requests', '0006_remove_request_unique_active_request_per_student'),
    ]

    operations = [
    ]
