# Generated by Django 5.2.16 on 2026-08-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_merge_20260803_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='supplement_requirements',
            field=models.JSONField(blank=True, default=list, verbose_name='Danh sách tài liệu yêu cầu bổ sung'),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='document_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Mã loại tài liệu'),
        ),
    ]
