# Generated by Django 6.0.3 on 2026-07-19 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='generated_document', serialize=False, to='requests.request')),
                ('pdf_file', models.FileField(upload_to='generated_docs/%Y/%m/%d/', verbose_name='Tệp PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tài liệu tự động',
                'verbose_name_plural': 'Các tài liệu tự động',
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='evidences/%Y/%m/%d/', verbose_name='Tệp tin')),
                ('file_type', models.CharField(max_length=100, verbose_name='Loại minh chứng')),
                ('upload_batch', models.PositiveIntegerField(default=1, verbose_name='Lần bổ sung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='requests.request', verbose_name='Yêu cầu')),
            ],
            options={
                'verbose_name': 'Minh chứng',
                'verbose_name_plural': 'Các minh chứng',
            },
        ),
    ]
