# Generated by Django 6.0.3 on 2026-07-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='evidences/%Y/%m/%d/', verbose_name='Tệp tin')),
                ('file_type', models.CharField(max_length=100, verbose_name='Loại minh chứng')),
                ('upload_batch', models.PositiveIntegerField(default=1, verbose_name='Lần bổ sung')),
            ],
            options={
                'verbose_name': 'Minh chứng',
                'verbose_name_plural': 'Các minh chứng',
            },
        ),
    ]
