# Generated by Django 6.0.3 on 2026-07-27 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='generated_document', serialize=False, to='requests.request')),
                ('pdf_file', models.FileField(upload_to='generated_docs/%Y/%m/%d/', verbose_name='Tệp PDF')),
            ],
            options={
                'verbose_name': 'Tài liệu tự động',
                'verbose_name_plural': 'Các tài liệu tự động',
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='requests.request', verbose_name='Yêu cầu'),
        ),
    ]
