# Generated by Django 5.2.16 on 2026-07-28 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_file', models.FileField(upload_to='ocr_uploads/')),
                ('document_type', models.CharField(choices=[('MAJOR_CHANGE_ADMISSION_LETTER', 'Giấy báo trúng tuyển'), ('MAJOR_CHANGE_GRADUATION_CERTIFICATE', 'Giấy chứng nhận tốt nghiệp THPT'), ('RETENTION_SIGNED_APPLICATION', 'Đơn bảo lưu đã ký'), ('DROPOUT_SIGNED_APPLICATION', 'Đơn thôi học đã ký'), ('RESUME_SIGNED_APPLICATION', 'Đơn học tiếp đã ký'), ('UNKNOWN', 'Không xác định')], default='UNKNOWN', max_length=64)),
                ('expected_title', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_match', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0, help_text='Độ tin cậy từ 0.0 đến 1.0')),
                ('detected_document_type', models.CharField(choices=[('MAJOR_CHANGE_ADMISSION_LETTER', 'Giấy báo trúng tuyển'), ('MAJOR_CHANGE_GRADUATION_CERTIFICATE', 'Giấy chứng nhận tốt nghiệp THPT'), ('RETENTION_SIGNED_APPLICATION', 'Đơn bảo lưu đã ký'), ('DROPOUT_SIGNED_APPLICATION', 'Đơn thôi học đã ký'), ('RESUME_SIGNED_APPLICATION', 'Đơn học tiếp đã ký'), ('UNKNOWN', 'Không xác định')], default='UNKNOWN', max_length=64)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_title', models.CharField(blank=True, max_length=500)),
                ('extracted_fields', models.JSONField(blank=True, default=dict)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('validation_reason', models.TextField(blank=True)),
                ('signature_required', models.BooleanField(default=False)),
                ('signature_present', models.BooleanField(default=False)),
                ('signature_type', models.CharField(choices=[('HANDWRITTEN', 'Chữ ký viết tay'), ('TYPED_NAME', 'Tên gõ bằng máy'), ('DIGITAL', 'Chữ ký số'), ('NOT_FOUND', 'Không tìm thấy'), ('UNCERTAIN', 'Không chắc chắn')], default='NOT_FOUND', max_length=20)),
                ('signature_confidence', models.FloatField(default=0.0)),
                ('signature_page', models.PositiveIntegerField(blank=True, null=True)),
                ('signature_evidence', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='ocr_integration.ocrjob')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
