# Generated by Django 5.2.16 on 2026-07-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrresult',
            name='signature_checks',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
