# Generated by Django 5.2.16 on 2026-07-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_integration', '0002_ocrresult_signature_checks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrjob',
            name='document_type',
            field=models.CharField(choices=[('MAJOR_CHANGE_ADMISSION_LETTER', 'Giấy báo trúng tuyển'), ('MAJOR_CHANGE_GRADUATION_CERTIFICATE', 'Giấy chứng nhận tốt nghiệp THPT'), ('MAJOR_CHANGE_SIGNED_APPLICATION', 'Đơn xin chuyển ngành đã ký'), ('RETENTION_SIGNED_APPLICATION', 'Đơn bảo lưu đã ký'), ('DROPOUT_SIGNED_APPLICATION', 'Đơn thôi học đã ký'), ('RESUME_SIGNED_APPLICATION', 'Đơn học tiếp đã ký'), ('UNKNOWN', 'Không xác định')], default='UNKNOWN', max_length=64),
        ),
        migrations.AlterField(
            model_name='ocrresult',
            name='detected_document_type',
            field=models.CharField(choices=[('MAJOR_CHANGE_ADMISSION_LETTER', 'Giấy báo trúng tuyển'), ('MAJOR_CHANGE_GRADUATION_CERTIFICATE', 'Giấy chứng nhận tốt nghiệp THPT'), ('MAJOR_CHANGE_SIGNED_APPLICATION', 'Đơn xin chuyển ngành đã ký'), ('RETENTION_SIGNED_APPLICATION', 'Đơn bảo lưu đã ký'), ('DROPOUT_SIGNED_APPLICATION', 'Đơn thôi học đã ký'), ('RESUME_SIGNED_APPLICATION', 'Đơn học tiếp đã ký'), ('UNKNOWN', 'Không xác định')], default='UNKNOWN', max_length=64),
        ),
    ]
