# Generated by Django 6.0.3 on 2026-07-27 08:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tên lớp')),
                ('class_id', models.CharField(max_length=100, unique=True, verbose_name='Mã lớp')),
            ],
            options={
                'verbose_name': 'Lớp',
                'verbose_name_plural': 'Lớp',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tên ngành')),
                ('major_id', models.CharField(max_length=100, unique=True, verbose_name='Mã ngành')),
            ],
            options={
                'verbose_name': 'Ngành',
                'verbose_name_plural': 'Ngành',
            },
        ),
    ]
