# Generated by Django 6.0.3 on 2026-07-27 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='students.major', verbose_name='Ngành'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('student_id', models.CharField(max_length=100, unique=True, verbose_name='Mã số sinh viên')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.class', verbose_name='Lớp')),
            ],
            options={
                'verbose_name': 'Sinh viên',
                'verbose_name_plural': 'Sinh viên',
            },
        ),
    ]
