# Generated by Django 5.2.16 on 2026-07-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='faculty_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tên khoa'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Số điện thoại'),
        ),
    ]
