# Generated by Django 6.0.7 on 2026-08-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_major_faculty_name_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='admission_threshold',
            field=models.FloatField(default=0.0, verbose_name='Điểm chuẩn chuyển ngành'),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_score',
            field=models.FloatField(default=0.0, verbose_name='Điểm nhập học'),
        ),
    ]
