# Generated by Django 6.0.3 on 2026-08-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_major_admission_threshold_student_admission_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_combo',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Tổ hợp xét tuyển'),
        ),
    ]
